<?php
session_start();
require 'vendor/autoload.php'; // Include Composer's autoload file
include('config.php');

$columns = isset($_GET['columns']) ? explode(',', $_GET['columns']) : [];
$month = isset($_GET['month']) ? $_GET['month'] : '';
$year = isset($_GET['year']) ? $_GET['year'] : '';
$user = isset($_SESSION['username']) ? $_SESSION['username'] : 'Guest';

if (empty($columns)) {
    die('No columns selected');
}

// Prepare SQL query based on selected columns
$columnMap = [
    'tanggal' => 'o.tanggal',
    'nomor_invoice' => 'o.nomor_invoice',
    'kode_buku' => 'o.kode_buku',
    'nama_buku' => 'p.nama_buku',
    'customer_name' => 'c.name AS customer_name',
    'kuantitas' => 'o.kuantitas',
    'harga_satuan' => 'o.harga_satuan',
    'subtotal' => '(o.kuantitas * o.harga_satuan) AS subtotal'
];

$selectedColumns = array_map(function ($col) use ($columnMap) {
    return isset($columnMap[$col]) ? $columnMap[$col] : $col;
}, $columns);

$sql = "SELECT " . implode(', ', $selectedColumns) . " 
        FROM outgoing o
        LEFT JOIN products p ON o.kode_buku = p.kode_buku
        LEFT JOIN customers c ON o.customer_id = c.id";

if ($month && $year) {
    $sql .= " WHERE MONTH(o.tanggal) = '$month' AND YEAR(o.tanggal) = '$year'";
} elseif ($year) {
    $sql .= " WHERE YEAR(o.tanggal) = '$year'";
}

$result = $conn->query($sql);

if (!$result) {
    die("Query failed: " . $conn->error);
}

$rows = $result->fetch_all(MYSQLI_ASSOC);

// Function to format currency
function formatRupiah($value) {
    return 'Rp ' . number_format($value, 0, ',', '.') . ',-';
}

// Function to format date
function formatTanggal($tanggal) {
    setlocale(LC_TIME, 'id_ID.utf8');
    $date = new DateTime($tanggal);
    return strftime('%d %B %Y', $date->getTimestamp());
}

// Generate PDF
$mpdf = new \Mpdf\Mpdf();
$html = '<h1>Report Outgoing</h1>';

$html .= '<table border="1" cellpadding="5" cellspacing="0" style="width: 100%;">';
$html .= '<thead><tr>';
foreach ($columns as $col) {
    $html .= '<th>' . ucfirst(str_replace('_', ' ', $col)) . '</th>';
}
$html .= '</tr></thead>';
$html .= '<tbody>';

$grandTotal = 0;
foreach ($rows as $row) {
    $html .= '<tr>';
    foreach ($columns as $col) {
        if ($col == 'harga_satuan' || $col == 'subtotal') {
            $html .= '<td>' . formatRupiah($row[$col]) . '</td>';
            if ($col == 'subtotal') {
                $grandTotal += $row[$col];
            }
        } elseif ($col == 'tanggal') {
            $html .= '<td>' . formatTanggal($row[$col]) . '</td>';
        } else {
            $html .= '<td>' . $row[$col] . '</td>';
        }
    }
    $html .= '</tr>';
}

$html .= '</tbody></table>';
$html .= '<p><strong>Grand Total: ' . formatRupiah($grandTotal) . '</strong></p>';

// // Tambahkan nama user di kanan bawah
// $html .= '<p style="text-align: right;">Generated by: ' . $user . '</p>';

$mpdf->WriteHTML($html);
$mpdf->Output('Report_Outgoing.pdf', 'I');
?>
